# Generated by Django 2.1.1 on 2018-12-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='管理员名字')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('role', models.CharField(max_length=100, verbose_name='角色')),
                ('add_room', models.IntegerField(verbose_name='添加房间')),
            ],
        ),
        migrations.CreateModel(
            name='Room_info',
            fields=[
                ('num', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='编号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('kind', models.CharField(max_length=100, verbose_name='类型')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
            ],
        ),
    ]
