# Generated by Django 2.1.1 on 2018-12-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment_info_customer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_room1', models.IntegerField(default='', verbose_name='大床房')),
                ('add_room2', models.IntegerField(default='', verbose_name='情侣房')),
                ('add_room3', models.IntegerField(default='', verbose_name='海底房')),
                ('add_room4', models.IntegerField(default='', verbose_name='三人房')),
                ('add_room5', models.IntegerField(default='', verbose_name='双人房')),
                ('add_room6', models.IntegerField(default='', verbose_name='单人房')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment_info',
            name='number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='手机号'),
        ),
    ]
