# Generated by Django 2.1.1 on 2018-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181217_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='room_kind',
            field=models.CharField(default=' ', max_length=100, verbose_name='房型'),
        ),
    ]
