# Generated by Django 2.1.1 on 2018-12-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_admin_info_add_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_info',
            name='room_kind',
        ),
    ]
